map:
  update-interval-ticks: 100
  position-delay-ticks: 100
  # Pilihan scale: CLOSEST, CLOSE, NORMAL, FAR, FARTHEST
  # CLOSEST: 1 pixel = 1 blok (paling dekat)
  # FARTHEST: 1 pixel = 16 blok (paling jauh, bisa melihat area sangat luas)
  scale: CLOSEST

event:
  # Minimal leader yang dibutuhkan untuk bisa memulai event (Default: 2, set 1 untuk testing/development)
  minimum-leaders: 2
  # Countdown saat leader utama offline (dalam detik). Default: 3600 (1 jam)
  # Leader tidak akan langsung dihapus, map akan dipindah ke backup leader
  leader-offline-countdown: 30

features:
  glowing:
    enabled: true
    # Interval glowing effect ke musuh (dalam detik). Default: 600 (10 menit)
    interval-seconds: 600
  
  radar:
    # Jarak deteksi musuh untuk action bar dan glowing effect (dalam block)
    distance: 200
  
  time-limit:
    enabled: true
    duration-seconds: 3600 # Waktu maksimal event (contoh 1 jam = 3600)
    
  kill-rewards:
    enabled: true
    heal-full: true # Regen darah sampai penuh
    # Daftar efek potion yang diberikan saat membunuh leader lain
    effects:
      - "SPEED:2:10" # Format: TIPE:LEVEL:DURASI_DETIK
  
  win-fireworks:
    # Durasi fireworks saat ada pemenang (dalam detik)
    duration-seconds: 5
    # Jumlah fireworks per detik
    fireworks-per-second: 3
