name: MapHunter
version: '${project.version}'
main: dev.pterox.maphunter.MapHunter
api-version: '1.20'
authors: [ Pterox ]
description: Advanced clan map tracking system

commands:
  rmh:
    description: Main command for MapHunter
    aliases:
      - rakamaphunter
    permission: maphunter.admin

permissions:
  maphunter.admin:
    description: Allows management of MapHunter plugin
    default: op
